"""create update salaries

Revision ID: 066f8d6b3a6e
Revises: b77612de7f7b
Create Date: 2026-03-29 07:56:07.404643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066f8d6b3a6e'
down_revision: Union[str, Sequence[str], None] = 'b77612de7f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salaries', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salaries', 'updated_at')
    # ### end Alembic commands ###
