"""create product image other

Revision ID: 47119a185eb3
Revises: ed7638c7050f
Create Date: 2026-03-25 14:46:40.124655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47119a185eb3'
down_revision: Union[str, Sequence[str], None] = 'ed7638c7050f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('categories', sa.Column('image_public_id', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('customers', sa.Column('avatar_public_id', sa.String(length=255), nullable=True))
    op.add_column('suppliers', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('suppliers', sa.Column('avatar_public_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'avatar_public_id')
    op.drop_column('suppliers', 'avatar_url')
    op.drop_column('customers', 'avatar_public_id')
    op.drop_column('customers', 'avatar_url')
    op.drop_column('categories', 'image_public_id')
    op.drop_column('categories', 'image_url')
    # ### end Alembic commands ###
