"""add reason

Revision ID: 7396a37f5247
Revises: 066f8d6b3a6e
Create Date: 2026-03-29 08:12:11.988402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7396a37f5247'
down_revision: Union[str, Sequence[str], None] = '066f8d6b3a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary_adjustments', sa.Column('reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary_adjustments', 'reason')
    # ### end Alembic commands ###
