"""update staff profile

Revision ID: 7ecb2d383c44
Revises: f1baac9f25fc
Create Date: 2026-03-25 13:32:49.409111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ecb2d383c44'
down_revision: Union[str, Sequence[str], None] = 'f1baac9f25fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ✅ Step 1: create ENUM type
    gender_enum = sa.Enum('male', 'female', 'other', name='genderenum')
    gender_enum.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('gender', gender_enum, nullable=True))
    op.add_column('staff', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('staff', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('staff', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('staff', sa.Column('avatar_public_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'avatar_public_id')
    op.drop_column('staff', 'avatar_url')
    op.drop_column('staff', 'address')
    op.drop_column('staff', 'date_of_birth')
    op.drop_column('staff', 'gender')
    # ### end Alembic commands ###
    # ✅ Step 2: drop ENUM type
    gender_enum = sa.Enum('male', 'female', 'other', name='genderenum')
    gender_enum.drop(op.get_bind(), checkfirst=True)
