"""fix 3 created_at server_default

Revision ID: 8aeb97186499
Revises: c350da888dd0
Create Date: 2026-03-22 05:04:45.107458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aeb97186499'
down_revision: Union[str, Sequence[str], None] = 'c350da888dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary_adjustments', 'reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary_adjustments', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
