"""fix created_at server_default

Revision ID: a3c41c366951
Revises: 27e3d57401b6
Create Date: 2026-03-22 04:17:10.028283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c41c366951'
down_revision: Union[str, Sequence[str], None] = '27e3d57401b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_group_members', sa.Column('staff_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('chat_group_members_user_id_fkey'), 'chat_group_members', type_='foreignkey')
    op.create_foreign_key(None, 'chat_group_members', 'staff', ['staff_id'], ['staff_id'])
    op.drop_column('chat_group_members', 'user_id')
    op.create_foreign_key('fk_department_manager', 'departments', 'users', ['manager_id'], ['user_id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_department_manager', 'departments', type_='foreignkey')
    op.add_column('chat_group_members', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_group_members', type_='foreignkey')
    op.create_foreign_key(op.f('chat_group_members_user_id_fkey'), 'chat_group_members', 'users', ['user_id'], ['user_id'])
    op.drop_column('chat_group_members', 'staff_id')
    # ### end Alembic commands ###
