""" update data chat message

Revision ID: c0078ca59697
Revises: c7791f415451
Create Date: 2026-04-12 17:26:44.794669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0078ca59697'
down_revision: Union[str, Sequence[str], None] = 'c7791f415451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('reply_to_id', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('publice', sa.String(length=500), nullable=True))
    op.add_column('chat_messages', sa.Column('media_thumbnail', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'chat_messages', 'chat_messages', ['reply_to_id'], ['message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'media_thumbnail')
    op.drop_column('chat_messages', 'publice')
    op.drop_column('chat_messages', 'reply_to_id')
    # ### end Alembic commands ###
