"""create invoice_attachment

Revision ID: c563f3367168
Revises: ba1f15033db5
Create Date: 2026-04-05 17:56:27.336632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c563f3367168'
down_revision: Union[str, Sequence[str], None] = 'ba1f15033db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_attachments',
    sa.Column('attachment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('public_id', sa.String(length=300), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_index(op.f('ix_invoice_attachments_company_id'), 'invoice_attachments', ['company_id'], unique=False)
    op.create_index(op.f('ix_invoice_attachments_invoice_id'), 'invoice_attachments', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_attachments_invoice_id'), table_name='invoice_attachments')
    op.drop_index(op.f('ix_invoice_attachments_company_id'), table_name='invoice_attachments')
    op.drop_table('invoice_attachments')
    # ### end Alembic commands ###
