"""update user staff

Revision ID: ed7638c7050f
Revises: 7ecb2d383c44
Create Date: 2026-03-25 14:00:43.726797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed7638c7050f'
down_revision: Union[str, Sequence[str], None] = '7ecb2d383c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('avatar_public_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_public_id')
    op.drop_column('users', 'avatar_url')
    op.drop_column('staff', 'updated_at')
    # ### end Alembic commands ###
