"""add  table company

Revision ID: f1baac9f25fc
Revises: 798fc5425497
Create Date: 2026-03-24 13:38:56.384135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1baac9f25fc'
down_revision: Union[str, Sequence[str], None] = '798fc5425497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('logo_public_id', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('banner_url', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('banner_public_id', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('companies', 'logo_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'logo_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'banner_public_id')
    op.drop_column('companies', 'banner_url')
    op.drop_column('companies', 'logo_public_id')
    # ### end Alembic commands ###
